name: Provision and Configure RHEL EC2

on:
  workflow_dispatch:  # Manual trigger from GitHub
  push:
    branches:
      - master         # Auto-trigger on push to master

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  configure:
    needs: provision
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Add SSH Key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/hosts.ini ansible/install_updates.yml --private-key key.pem
        env:
          ANSIBLE_HOST_KEY_CHECKING: False